language: ruby
sudo: required
dist: trusty
rvm:
  - 2.6
  - 2.5
  - 2.4
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-3
