language: ruby
sudo: required
dist: trusty
rvm:
  - 2.3
  - 2.2
  - 2.1
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-3
matrix:
  allow_failures:
    rvm:
      - ruby-head
      - jruby-19mode
      - jruby-head
      - rbx-3
